import XCTest
@testable import CLI
@testable import MacParakeetCore

final class MeetingsCommandTests: XCTestCase {
    func testMeetingsCommandIsRegisteredAtTopLevel() {
        XCTAssertTrue(
            CLI.configuration.subcommands.contains { $0 == MeetingsCommand.self },
            "meetings must be available from macparakeet-cli"
        )
    }

    func testExecutableSubcommandsParse() throws {
        XCTAssertNoThrow(try MeetingsCommand.ListSubcommand.parse(["--json"]))
        XCTAssertNoThrow(try MeetingsCommand.ShowSubcommand.parse(["abcd", "--json"]))
        XCTAssertNoThrow(try MeetingsCommand.TranscriptSubcommand.parse(["abcd", "--format", "srt"]))
        XCTAssertNoThrow(try MeetingsCommand.NotesSubcommand.AppendSubcommand.parse(["abcd", "--text", "Decision: ship"]))
        XCTAssertNoThrow(try MeetingsCommand.NotesSubcommand.ClearSubcommand.parse(["abcd", "--json"]))
        XCTAssertNoThrow(try MeetingsCommand.ResultsSubcommand.ListSubcommand.parse(["abcd", "--json"]))
        XCTAssertNoThrow(try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse(["abcd", "--name", "Agent Notes", "--content", "Decision: ship", "--json"]))
        XCTAssertNoThrow(try MeetingsCommand.ExportSubcommand.parse(["abcd", "--format", "md", "--stdout"]))
    }

    func testListRejectsNegativeLimit() {
        XCTAssertThrowsError(try MeetingsCommand.ListSubcommand.parse(["--limit", "-1"]))
    }

    func testNotesSetRequiresOneInputSource() {
        XCTAssertThrowsError(try MeetingsCommand.NotesSubcommand.SetSubcommand.parse(["abcd"]))
        XCTAssertThrowsError(
            try MeetingsCommand.NotesSubcommand.SetSubcommand.parse(["abcd", "--text", "note", "--stdin"])
        )
        XCTAssertNoThrow(try MeetingsCommand.NotesSubcommand.SetSubcommand.parse(["abcd", "--text", "note"]))
        XCTAssertNoThrow(try MeetingsCommand.NotesSubcommand.SetSubcommand.parse(["abcd", "--stdin"]))
    }

    func testNotesAppendRequiresOneInputSource() {
        XCTAssertThrowsError(try MeetingsCommand.NotesSubcommand.AppendSubcommand.parse(["abcd"]))
        XCTAssertThrowsError(
            try MeetingsCommand.NotesSubcommand.AppendSubcommand.parse(["abcd", "--text", "note", "--stdin"])
        )
        XCTAssertNoThrow(try MeetingsCommand.NotesSubcommand.AppendSubcommand.parse(["abcd", "--text", "note"]))
        XCTAssertNoThrow(try MeetingsCommand.NotesSubcommand.AppendSubcommand.parse(["abcd", "--stdin"]))
    }

    func testResultsAddRequiresNameAndOneInputSource() {
        XCTAssertThrowsError(try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse(["abcd", "--name", "Result"]))
        XCTAssertThrowsError(
            try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse([
                "abcd", "--name", "Result", "--content", "body", "--stdin"
            ])
        )
        XCTAssertThrowsError(
            try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse([
                "abcd", "--name", "   ", "--content", "body"
            ])
        )
        XCTAssertNoThrow(
            try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse([
                "abcd", "--name", "Result", "--content", "body"
            ])
        )
        XCTAssertNoThrow(
            try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse([
                "abcd", "--name", "Result", "--stdin"
            ])
        )
    }

    func testResultsAddStoresPromptResultForMeeting() async throws {
        let dbURL = temporaryDatabaseURL()
        defer { try? FileManager.default.removeItem(at: dbURL) }
        let db = try DatabaseManager(path: dbURL.path)
        let transcriptionRepo = TranscriptionRepository(dbQueue: db.dbQueue)
        let resultRepo = PromptResultRepository(dbQueue: db.dbQueue)
        let meeting = Transcription(
            fileName: "Design Review",
            rawTranscript: "We agreed to ship the parser.",
            status: .completed,
            sourceType: .meeting,
            userNotes: "Manual note"
        )
        try transcriptionRepo.save(meeting)

        let command = try MeetingsCommand.ResultsSubcommand.AddSubcommand.parse([
            meeting.id.uuidString,
            "--name", "Agent Notes",
            "--content", "Decision: ship the parser.",
            "--prompt-content", "Extract decisions.",
            "--extra", "Generated by external agent.",
            "--json",
            "--database", dbURL.path,
        ])
        let output = try await captureStandardOutput {
            try await command.run()
        }
        let payload = try XCTUnwrap(
            JSONSerialization.jsonObject(with: Data(output.utf8)) as? [String: Any]
        )

        XCTAssertEqual(payload["meetingTitle"] as? String, "Design Review")
        XCTAssertEqual(payload["name"] as? String, "Agent Notes")
        XCTAssertEqual(payload["content"] as? String, "Decision: ship the parser.")
        XCTAssertEqual(payload["userNotesSnapshot"] as? String, "Manual note")

        let saved = try resultRepo.fetchAll(transcriptionId: meeting.id)
        XCTAssertEqual(saved.count, 1)
        XCTAssertEqual(saved[0].promptName, "Agent Notes")
        XCTAssertEqual(saved[0].promptContent, "Extract decisions.")
        XCTAssertEqual(saved[0].extraInstructions, "Generated by external agent.")
        XCTAssertEqual(saved[0].content, "Decision: ship the parser.")
        XCTAssertEqual(saved[0].userNotesSnapshot, "Manual note")
    }

    func testFormatRawValues() {
        XCTAssertEqual(MeetingTranscriptFormat(rawValue: "text"), .text)
        XCTAssertEqual(MeetingTranscriptFormat(rawValue: "json"), .json)
        XCTAssertEqual(MeetingTranscriptFormat(rawValue: "srt"), .srt)
        XCTAssertEqual(MeetingTranscriptFormat(rawValue: "vtt"), .vtt)
        XCTAssertEqual(MeetingExportFormat(rawValue: "md"), .md)
        XCTAssertEqual(MeetingExportFormat(rawValue: "json"), .json)
    }

    private func temporaryDatabaseURL() -> URL {
        FileManager.default.temporaryDirectory
            .appendingPathComponent("macparakeet-cli-meetings-\(UUID().uuidString).db")
    }
}
